Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# entropy data target
initial_data_target_entropy = count_entropy(countEveryCategory(target_data, labels, target_data.columns[0], target_data.columns[1]))
------------------

[0;31m[0m
[0;31mKeyError[0mTraceback (most recent call last)
[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py[0m in [0;36mget_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   3360[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3361[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mcasted_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3362[0m             [0;32mexcept[0m [0mKeyError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/_libs/index.pyx[0m in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/_libs/index.pyx[0m in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

[0;32mpandas/_libs/hashtable_class_helper.pxi[0m in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;32mpandas/_libs/hashtable_class_helper.pxi[0m in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 'sedikit_lebar'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0mTraceback (most recent call last)
[0;32m<ipython-input-67-91aff78ce74a>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# entropy data target[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0minitial_data_target_entropy[0m [0;34m=[0m [0mcount_entropy[0m[0;34m([0m[0mcountEveryCategory[0m[0;34m([0m[0mtarget_data[0m[0;34m,[0m [0mlabels[0m[0;34m,[0m [0mtarget_data[0m[0;34m.[0m[0mcolumns[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mtarget_data[0m[0;34m.[0m[0mcolumns[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-62-bc97a9253bfb>[0m in [0;36mcountEveryCategory[0;34m(data_column, labels, column, category)[0m
[1;32m      4[0m     [0mamount_of_every_category[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0;32mfor[0m [0mlabel[0m [0;32min[0m [0mlabels[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 6[0;31m         [0mamount_of_every_category[0m[0;34m.[0m[0mappend[0m[0;34m([0m[0mgroup[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0mlabel[0m[0;34m,[0m [0mcolumn[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      7[0m     [0;32mreturn[0m [0mamount_of_every_category[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    923[0m                 [0;32mwith[0m [0msuppress[0m[0;34m([0m[0mKeyError[0m[0;34m,[0m [0mIndexError[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    924[0m                     [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mobj[0m[0;34m.[0m[0m_get_value[0m[0;34m([0m[0;34m*[0m[0mkey[0m[0;34m,[0m [0mtakeable[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0m_takeable[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 925[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_tuple[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    926[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    927[0m             [0;31m# we by definition only have the 0th axis[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py[0m in [0;36m_getitem_tuple[0;34m(self, tup)[0m
[1;32m   1098[0m     [0;32mdef[0m [0m_getitem_tuple[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mtup[0m[0;34m:[0m [0mtuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1099[0m         [0;32mwith[0m [0msuppress[0m[0;34m([0m[0mIndexingError[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1100[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_getitem_lowerdim[0m[0;34m([0m[0mtup[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1101[0m [0;34m[0m[0m
[1;32m   1102[0m         [0;31m# no multi-index, so validate all of the indexers[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py[0m in [0;36m_getitem_lowerdim[0;34m(self, tup)[0m
[1;32m    836[0m                 [0;31m# We don't need to check for tuples here because those are[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    837[0m                 [0;31m#  caught by the _is_nested_tuple_indexer check above.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 838[0;31m                 [0msection[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_getitem_axis[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0mi[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    839[0m [0;34m[0m[0m
[1;32m    840[0m                 [0;31m# We should never have a scalar section here, because[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py[0m in [0;36m_getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1162[0m         [0;31m# fall thru to straight lookup[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1163[0m         [0mself[0m[0;34m.[0m[0m_validate_key[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1164[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_label[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1165[0m [0;34m[0m[0m
[1;32m   1166[0m     [0;32mdef[0m [0m_get_slice_axis[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mslice_obj[0m[0;34m:[0m [0mslice[0m[0;34m,[0m [0maxis[0m[0;34m:[0m [0mint[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py[0m in [0;36m_get_label[0;34m(self, label, axis)[0m
[1;32m   1111[0m     [0;32mdef[0m [0m_get_label[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mlabel[0m[0;34m,[0m [0maxis[0m[0;34m:[0m [0mint[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1112[0m         [0;31m# GH#5667 this will fail if the label is not present in the axis.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1113[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mobj[0m[0;34m.[0m[0mxs[0m[0;34m([0m[0mlabel[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1114[0m [0;34m[0m[0m
[1;32m   1115[0m     [0;32mdef[0m [0m_handle_lowerdim_multi_index_axis0[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mtup[0m[0;34m:[0m [0mtuple[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py[0m in [0;36mxs[0;34m(self, key, axis, level, drop_level)[0m
[1;32m   3774[0m                 [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0;34mf"Expected label or tuple of labels, got {key}"[0m[0;34m)[0m [0;32mfrom[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3775[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3776[0;31m             [0mloc[0m [0;34m=[0m [0mindex[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3777[0m [0;34m[0m[0m
[1;32m   3778[0m             [0;32mif[0m [0misinstance[0m[0;34m([0m[0mloc[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mndarray[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py[0m in [0;36mget_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   3357[0m                     [0;34m"backfill or nearest lookups"[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3358[0m                 )
[0;32m-> 3359[0;31m             [0mcasted_key[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_maybe_cast_indexer[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3360[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3361[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mcasted_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/category.py[0m in [0;36m_maybe_cast_indexer[0;34m(self, key)[0m
[1;32m    482[0m         [0;31m#  because this will correctly get partial-indexing on Interval categories[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    483[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 484[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_data[0m[0;34m.[0m[0m_unbox_scalar[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    485[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    486[0m             [0;32mif[0m [0mis_valid_na_for_dtype[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mcategories[0m[0;34m.[0m[0mdtype[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/arrays/categorical.py[0m in [0;36m_unbox_scalar[0;34m(self, key)[0m
[1;32m   1869[0m         [0;31m# searchsorted is very performance sensitive. By converting codes[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1870[0m         [0;31m# to same dtype as self.codes, we get much faster performance.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1871[0;31m         [0mcode[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mcategories[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1872[0m         [0mcode[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_ndarray[0m[0;34m.[0m[0mdtype[0m[0;34m.[0m[0mtype[0m[0;34m([0m[0mcode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1873[0m         [0;32mreturn[0m [0mcode[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py[0m in [0;36mget_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   3361[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_engine[0m[0;34m.[0m[0mget_loc[0m[0;34m([0m[0mcasted_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3362[0m             [0;32mexcept[0m [0mKeyError[0m [0;32mas[0m [0merr[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 3363[0;31m                 [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m [0;32mfrom[0m [0merr[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3364[0m [0;34m[0m[0m
[1;32m   3365[0m         [0;32mif[0m [0mis_scalar[0m[0;34m([0m[0mkey[0m[0;34m)[0m [0;32mand[0m [0misna[0m[0;34m([0m[0mkey[0m[0;34m)[0m [0;32mand[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0mhasnans[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'sedikit_lebar'
KeyError: 'sedikit_lebar'

